### ISSUE TITLE
wordcount example throws an error

### ISSUE THREAD

**Issue by bast** [coderefinery/reproducible-research#186]
Participant reported this and I get the same error:
```console
$ python source/plotcount.py data/isles.txt processed_data/isles.png

Traceback (most recent call last):
  File "/home/user/course/word-count/source/plotcount.py", line 31, in <module>
    counts = load_word_counts(input_file)
  File "/home/user/course/word-count/source/wordcount.py", line 37, in load_word_counts
    counts.append((fields[0], int(fields[1]), float(fields[2])))
ValueError: invalid literal for int() with base 10: 'JOURNEY'
```

I am not sure where in the lesson this was run but I think when we explored the word-count example.

**Comment by bast** [comment]
Ah I see the mixup I think.
